package utils

import (
	"fmt"
	"strings"
)

type ConfigParams struct {
	Name        string
	IP          string
	Community   string
	Password    string
	Supernode   string
	Mac         string
	Encryption  string // AES, Twofish, ChaCha20, Speck
	Compression bool
	Routing     string
	LocalPort   int
}

func formatMac(mac string) string {
	if len(mac) != 12 {
		return mac
	}
	var res []string
	for i := 0; i < 12; i += 2 {
		res = append(res, mac[i:i+2])
	}
	return strings.Join(res, ":")
}

func getEncryptionFlag(enc string) string {
	switch enc {
	case "Twofish":
		return "-A2"
	case "ChaCha20":
		return "-A4"
	case "Speck":
		return "-A5"
	default:
		return "-A3" // AES
	}
}

func GenerateConfFile(p ConfigParams) string {
	var sb strings.Builder
	sb.WriteString("# n2n Edge Configuration Generated by n2n_ui\n")
	sb.WriteString(fmt.Sprintf("# Node Name: %s\n\n", p.Name))

	sb.WriteString("-d=n2n0\n")
	sb.WriteString(fmt.Sprintf("-a=%s\n", p.IP))
	sb.WriteString(fmt.Sprintf("-c=%s\n", p.Community))
	sb.WriteString(fmt.Sprintf("-k=%s\n", p.Password))
	sb.WriteString(fmt.Sprintf("-l=%s\n", p.Supernode))
	sb.WriteString(fmt.Sprintf("-m=%s\n", formatMac(p.Mac)))
	sb.WriteString(fmt.Sprintf("-I=%s\n", p.Name))
	sb.WriteString(fmt.Sprintf("%s\n", getEncryptionFlag(p.Encryption)))

	if p.LocalPort > 0 {
		sb.WriteString(fmt.Sprintf("-p=%d\n", p.LocalPort))
	}
	if p.Compression {
		sb.WriteString("-z1\n")
	}
	if p.Routing != "" {
		sb.WriteString(fmt.Sprintf("-n=%s\n", p.Routing))
	}

	// Always foreground for easy service management, -f is safe for systemd too
	sb.WriteString("-f\n")

	return sb.String()
}